#group:
#  group_name: <group_name>
#  component_name: <component_name>
#  buttons: [[button_name1,function_name1,parameter_name2,
#    [button_name2,function_name2,parameter_name2]]

group1:
  group_name: arm settings
  component_name: arm
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [recover,trigger,recover],
    [undefined mode,mode,undefined],
    [position mode,mode,position],
    [velocity mode,mode,velocity],
    [gravcomp mode,mode,gravcomp]]
group2:
  group_name: arm pos
  component_name: arm
  buttons: [[stop,trigger,stop],
    [home,move,home],
    [folded,move,folded],
    [pregrasp,move,pregrasp],
    [hold,move,hold],
    [overtray,move,overtray],
    [tray,move,tray],
    [wave in,move,wavein],
    [wave out,move,waveout]]
group3:
  group_name: arm traj
  component_name: arm
  buttons: [[stop,trigger,stop],
    [folded-to-look at table,move,folded-to-look_at_table],
    [look_at_table-to-folded,move,look_at_table-to-folded],
    [grasp-to-tray,move,grasp-to-tray],
    [tray-to-folded,move,tray-to-folded],
    [wave,move,wave]]
group4:
  group_name: sdh
  component_name: sdh
  buttons: [[stop,trigger,stop],
    [init,trigger,init],
    [home,move,home],
    [cyl. closed,move,cylclosed],
    [cyl. open,move,cylopen],
    [spher. closed,move,spherclosed],
    [spher. open,move,spheropen],
    [point,move,point],
    [fist,move,fist]]
